### ISSUE TITLE
Any parameters to set the Gel Concentration?

### ISSUE THREAD

**Issue by tao-bioinfo** [squarednob/d3-electrophoresis#1]
In http://biocompute.bmi.ac.cn/CZlab/ve/ (also an online program for simulating electrophoresis on agarose gel), there is a Gel Concentration parameter setting. Is it also possible implemented here? It seems have significant change under different Gel Concentrations for the same marker and band sizes:

0.5% agarose gel image:
http://pic.yupoo.com/stillwater02_v/GmA0Krlx/ZVFvA.png

2% agarose gel image:
http://pic.yupoo.com/stillwater02_v/GmA0KCLS/Zfelv.png

**Comment by squarednob** [comment]
Hi, if gel concentration in http://biocompute.bmi.ac.cn/CZlab/ve/ means changing scale of bands, it can also be implemented in d3-electrophoresis.js.
"electrophoresis.scale(d3.scale~)" takes responsibility for scale, and you can change scale by changing input of "d3.scale~", such as "d3.scaleLinear()", "d3.scaleSqrt()".

[Example page for changing scale](https://bl.ocks.org/squarednob/raw/959bac1f4eca03059e02dbd480982c60/). You can change scale by turning on/off "Square Root Scale".

Example code:
```javascript
var gel = electrophoresis();

var svg = d3.select("body").append("svg")
  .attr("width", 460)
  .attr("height", 500)
  .call(gel.makeGel);

var text = "AGCGCCCAATACGCAAACCGCCTCTCCCCGCGCGTTGGCCGATTCACGTTTACGAGTTGGAAACGA";
var words = [[1,5,10,15,20,30,40,50,70,100],"CAAA","GTTGG","GGATCC", "GA",["GT","CCT"],"ACC", "GAAA"];
var names = ["marker", "1", "2", "3", "4", "5", "6", "7"];
// Add chain of .scale(d3.scale~()).
gel = electrophoresis().DNA(text).enzymes(words).names(names).scale(d3.scaleSqrt());
svg.call(gel);
```

If you want to relate scale with percentage of agarose gel concentration, you can probably customize scale object by using domain() and range() chain of d3.scale~ or using [d3.scaleSequential](https://github.com/d3/d3-scale/blob/master/README.md#sequential-scales).
