### ISSUE TITLE
When should we use scaleSqrt ?

### ISSUE THREAD

**Issue by tao-bioinfo** [squarednob/d3-electrophoresis#2]
The default is scaleLinear. I'm not sure when should we use scaleSqrt. I tried the demo in https://bl.ocks.org/squarednob/raw/959bac1f4eca03059e02dbd480982c60/ . It seems as if the output image has some differences when turning on/off Square Root Scale. But I'm not sure what the biological meaning is

**Comment by squarednob** [comment]
First, I fixed a bug that .range() wan't reflect scale, and update d3-electrophoresis.js.
Now you can limit vertical band location, like [changing concentration of agarose gel](http://pic.yupoo.com/stillwater02_v/GmA0Krlx/ZVFvA.png). Demo and code: [d3-electrophoresis scale change range1](https://bl.ocks.org/squarednob/fc711a3e6a25800efbf03067b0231825).
The snippet below shows part of code to limit y=200~400 in linear scale.
```js
var yScale = d3.scaleLinear().range([200,400]);
gel = electrophoresis({DNA: text}).enzymes(words).names(names).scale(yScale);
```

.scale() is used for non-linear vertical distribution of bands. Like the [image](http://pic.yupoo.com/stillwater02_v/GmA0KCLS/Zfelv.png), band distribution is sometimes not linear. For example, length of 100-250bp is longer than 750-1000bp in the image.

And d3.scaleSqrt() is a d3's built-in scale module ([d3/d3-scale](https://github.com/d3/d3-scale)). You can also use other scale modules, such as d3.scalePow(), d3.scaleLog(), .etc. The scale modules can be used to convert linear number list into non-linear number list, for example. [0.1, 0.2, 0.3, 0.4] into [0.1, 0.15, 0.22, 0.4].
d3.scaleSqrt().range([10,30]) changes min/max range of converted list.
.scale() takes the scale module as argument and use the scale as vertical distribution.

I add tips section in github top page of d3-electrophoresis. If there is any unclear point, please reply the comment.

**Comment by AJ5101451717** [comment]
I love the business.  I didn’t know if you liked me up or not.
